import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const course=JSON.parse(fs.readFileSync('curriculum.json','utf8'));
const app=fs.readFileSync('app.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const api=fs.readFileSync('netlify/functions/api.mts','utf8');
const migration=fs.readFileSync('netlify/database/migrations/002_google-identity/migration.sql','utf8');
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));

test('pilot contains the four chapters in order',()=>{assert.deepEqual(course.blocks.map(b=>b.title),['AI & Me','Teaching a Machine','Data Detective','Generative AI & Prompting'])});
test('chapter durations match the student book and the Phase 4 and 5 contracts',()=>{assert.equal(course.blocks[0].sessions.reduce((n,s)=>n+s.minutes,0),120);assert.equal(course.blocks[1].sessions.reduce((n,s)=>n+s.minutes,0),240);assert.equal(course.blocks[2].sessions.reduce((n,s)=>n+s.minutes,0),180);assert.equal(course.blocks[3].sessions.reduce((n,s)=>n+s.minutes,0),240)});
test('student book learning outcomes and badges are preserved',()=>{assert.deepEqual(course.blocks[0].outcomes,['LO1','LO4']);assert.equal(course.blocks[0].badge,'AI Explorer');assert.deepEqual(course.blocks[1].outcomes,['LO1','LO2','LO3','LO9']);assert.equal(course.blocks[1].badge,'Machine Trainer');assert.deepEqual(course.blocks[2].outcomes,['LO5','LO6','LO9']);assert.equal(course.blocks[2].badge,'Data Detective');assert.deepEqual(course.blocks[3].outcomes,['LO7','LO9']);assert.equal(course.blocks[3].badge,'Prompt Engineer')});
test('every session includes study material before student response',()=>{for(const b of course.blocks)for(const s of b.sessions){assert.ok(s.pageRef.includes('Student Book'));assert.ok(s.study.body.length>=2);assert.ok(s.study.keywords.length>=3);assert.ok(s.reflection.length>20)}});
test('chapter 1 mission requires five systems and full chains',()=>{assert.match(course.blocks[0].mission,/five systems/i);assert.match(course.blocks[0].mission,/INPUT.*AI ACTION.*OUTPUT.*BENEFIT.*RISK/i)});
test('chapter 2 includes test log, confusion matrix and shortcut learning',()=>{const kinds=course.blocks[1].sessions.map(s=>s.activity.kind);assert.ok(kinds.includes('testlog'));assert.ok(kinds.includes('matrix'));assert.ok(course.blocks[1].sessions.some(s=>/shortcut/i.test(s.title+s.study.title)))});
test('chapter 3 follows the student book route, mission and portfolio',()=>{const b=course.blocks[2];assert.deepEqual(b.sessions.map(s=>s.id),['b3s1','b3s2','b3s3','b3s4','b3s5','b3s6']);assert.deepEqual(b.sessions.map(s=>s.activity.kind),['quiz','lab','chain','dataset','textfields','textfields']);assert.match(b.mission,/^Audit one digital service at category level/);assert.deepEqual(b.route.map(r=>r[1]),['Data trail warm-up','Data Tracking Sherlock','Why collect it?','Cookie and scraping mini-lab','Dataset fairness challenge','Discover: your rights and the safeguards','Design a better data plan','Reflection']);assert.equal(b.myths.length,3);assert.deepEqual(Object.keys(b.selfCheck),['Getting started','Getting there','Going further']);assert.match(b.levelUp,/^Compare two services that do a similar job/);for(const s of b.sessions)assert.equal(s.pageRef,'Student Book pp. 14–17')});
test('chapter 4 follows the student book route, mission, sessions and portfolio',()=>{const b=course.blocks[3];assert.equal(b.id,'block4');assert.equal(b.duration,'4 hours');assert.deepEqual(b.sessions.map(s=>s.id),['b4s1','b4s2','b4s3','b4s4','b4s5','b4s6','b4s7','b4s8','b4s9','b4s10']);assert.deepEqual(b.sessions.map(s=>s.minutes),[20,20,30,30,30,30,25,30,20,5]);assert.deepEqual(b.sessions.map(s=>s.activity.kind),['lab','quiz','prompt','prompt','chain','chain','textfields','textfields','textfields','textfields']);assert.equal(b.mission,'Run a three-version prompt experiment: v1 weak, v2 improved, v3 tested and revised. Keep the outputs. Then produce a verification log for at least three factual claims the AI made.');assert.deepEqual(b.route.map(r=>r[1]),['Same task, different prompts','Discover: what an LLM actually does','Prompt Lab 1: C-T-C-F','Prompt Lab 2: iterate','Four useful roles','Verification challenge','Injecting doubt','Build a reusable prompt','Peer red-team','Exit rule']);assert.match(b.final,/^Prompts v1, v2, v3 with their outputs \(Sheet A4\)/);assert.equal(b.myths.length,4);assert.equal(b.myths[0][0],'Longer prompts are always better.');assert.deepEqual(b.selfCheck,{'Getting started':['I can write a usable prompt','I notice when outputs differ'],'Getting there':['I improve prompts systematically','I verify important factual claims'],'Going further':['I build criteria to judge outputs','I compare outputs critically','I can explain how framing and confirmation bias affect results']});assert.match(b.levelUp,/^Write an evaluation rubric with four criteria\./);for(const s of b.sessions)assert.equal(s.pageRef,'Student Book pp. 18–22');const kw=new Set(b.sessions.flatMap(s=>s.study.keywords));for(const k of ['generative AI','large language model (LLM)','pattern prediction','prompt','context','constraint','output format','iteration','hallucination','verification','source quality'])assert.ok(kw.has(k),k);assert.ok(b.sessions.find(s=>s.id==='b4s2').study.body.some(p=>p.includes('Confident wording is not confident truth.')));assert.equal(b.sessions.find(s=>s.id==='b4s10').reflection,'Which moment in this chapter gave you that rule, and what exactly did you see?')});
test('chapter 4 prompt, quiz and chain activities carry the Phase 5 contract shapes',()=>{const s=id=>course.blocks[3].sessions.find(x=>x.id===id).activity;assert.equal(s('b4s2').title,'Pattern prediction or fact lookup?');assert.equal(s('b4s2').items.length,8);assert.deepEqual(s('b4s2').options,['Pattern prediction','Checked fact lookup','Neither']);assert.equal(s('b4s3').builder,true);assert.deepEqual(s('b4s3').versions,[['v1','V1 – baseline (the weak prompt)'],['v2','V2 – rebuilt with C-T-C-F']]);assert.deepEqual(s('b4s3').fields.map(f=>f[0]),['prompt','change','output','better']);assert.equal(s('b4s4').builder,false);assert.deepEqual(s('b4s4').versions,[['v3','V3 – tested and revised']]);assert.deepEqual(s('b4s4').fields,s('b4s3').fields);assert.equal(s('b4s4').extras.length,2);assert.deepEqual(s('b4s5').columns.map(c=>c[0]),['role','prompt','did','risk']);assert.equal(s('b4s5').minRows,4);assert.deepEqual(s('b4s6').columns.map(c=>c[0]),['claim','source','verdict','changed']);assert.equal(s('b4s6').minRows,3);assert.equal(s('b4s6').head,'CLAIM → SOURCE → VERDICT → WHAT I CHANGED');assert.equal(s('b4s7').fields.length,4);assert.equal(s('b4s8').fields.length,4);assert.equal(s('b4s9').fields.length,4);assert.deepEqual(s('b4s10').fields,['I should never trust an AI answer just because…'])});
test('next chapter is gated by previous chapter practical completion and capstone qualification',()=>{assert.match(app,/blockDone\(COURSE\.blocks\[i-1\]\).*blockQualified\(COURSE\.blocks\[i-1\]\)/)});
test('frontend uses Google OAuth and removes custom account creation',()=>{assert.match(app,/oauthLogin\('google'\)/);assert.doesNotMatch(app,/studentPin|studentCode|Create account/);assert.match(index,/Continue with Google/)});
test('server verifies Netlify Identity rather than custom session cookies',()=>{assert.match(api,/getUser.*@netlify\/identity/s);assert.doesNotMatch(api,/SESSION_SECRET|verifyPin|student_code/)});
test('identity database stores only identity id and display name, not a duplicate email',()=>{assert.match(migration,/identity_user_id/);assert.match(migration,/learner_progress/);assert.doesNotMatch(migration,/email\s+TEXT/i)});
test('Vite production build and Netlify Identity dependency are configured',()=>{assert.equal(pkg.scripts.build,'vite build');assert.ok(pkg.dependencies['@netlify/identity']);assert.ok(pkg.devDependencies.vite)});
